---
title: "EM2021_matchfacit"
author: "Richard Öhrvall"
date: '2021-06-06'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# EM 2021 - matchfacit

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)

```


Skapa ett facit över matcherna 1-51. 

Läs in Excel-fil med facit

```{r}
grund <- read_excel(here("data/tips", "EM-tipset2021_facit.xlsx"),
                    range = "B5:E40", col_names = FALSE) %>% 
  clean_names() %>% 
  select(-x3) %>% 
  mutate(match = row_number(),
         x1 = str_sub(x1, 4),
         x1 = str_replace_all(x1, "–", "-")) %>% 
  separate(x1, c("facit_hemmalag", "facit_bortalag"), sep = "-") %>% 
  rename(facit_hemmamal = x2,
         facit_bortamal = x4) %>% 
  mutate(across(where(is.character), str_trim)) %>%
  relocate(match)

slutspel <- read_excel(here("data/tips", "EM-tipset2021_facit.xlsx"),
                    range = "I8:R53", col_names = FALSE) %>% 
  clean_names() %>% 
  filter(!is.na(x5) & str_sub(x5, 1, 1) != "T") %>% 
  select(-x2, -x4, -x6, -x8) %>% 
  mutate(match = row_number() + 36,
         x5 = as.integer(x5)) %>% 
  rename(facit_hemmalag = x1,
         facit_bortalag = x3,
         facit_hemmamal = x5,
         facit_bortamal = x7,
         facit_extra = x9,
         facit_extra_vinnare = x10) %>% 
  mutate(across(where(is.character), str_trim)) %>% 
  relocate(match) 

facit <- grund %>% 
  bind_rows(slutspel)

```

Lägg ut

```{r}
write_csv2(facit, here("data/tips", "em2021_facit.csv"))

```

