---
title: "em2021_processing"
author: "Richard Öhrvall"
date: '2021-06-06'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EM-tips 2021: dataförberedelse

```{r}
library(tidyverse)
library(readxl)
library(janitor)
library(here)
library(fs)

```


Skapa en funktion för att läsa in Excel-filer och rensa upp i dem och skapa ett strukturerat dataset

```{r}

em2021_clean <- function(indatafil) {
  grund <- read_excel(indatafil,
                    range = "B5:E40", col_names = FALSE) %>% 
  clean_names() %>% 
  select(-x3) %>% 
  mutate(match = row_number(),
         x1 = str_sub(x1, 4),
         x1 = str_replace_all(x1, "–", "-")) %>% 
  separate(x1, c("hemmalag", "bortalag"), sep = "-") %>% 
  rename(hemmamal = x2,
         bortamal = x4) %>% 
  relocate(match)

slutspel <- read_excel(indatafil,
                    range = "I8:R53", col_names = FALSE) %>% 
  clean_names() %>% 
  filter(!is.na(x5) & str_sub(x5, 1, 1) != "T") %>% 
  select(-x2, -x4, -x6, -x8) %>% 
  mutate(match = row_number() + 36,
         x5 = as.integer(x5)) %>% 
  rename(hemmalag = x1,
         bortalag = x3,
         hemmamal = x5,
         bortamal = x7,
         extra = x9,
         extra_vinnare = x10) %>% 
  relocate(match)

skytteliga <- read_excel(indatafil,
                    range = "B44", col_names = FALSE) %>% 
  clean_names() %>% 
  mutate(bonus = "Skytteliga") %>% 
  rename(skytteliga_vinnare = x1) %>% 
  relocate(bonus)

namn <- read_excel(indatafil,
                    range = "I56", col_names = FALSE) %>% 
  clean_names() %>% 
  rename(namn = x1)
  
slutspelslag <- read_excel(indatafil,
                           sheet = "Blad2",
                    range = "C4:C38", col_names = FALSE) %>% 
  clean_names()  %>% 
  filter(!is.na(x1)) %>% 
  mutate(slutspelsomgang = case_when(row_number() <= 16 ~ "Åttondel",
                           between(row_number(), 17, 24) ~ "Kvartsfinal",
                           between(row_number(), 25, 28) ~ "Semifinal",
                           between(row_number(), 29, 30) ~ "Final",
                           row_number() == 31 ~ "Vinnare")) %>% 
  rename(slutspelslag = x1) %>% 
  relocate(slutspelsomgang)
  
tips <- grund %>% 
  bind_rows(slutspel) %>% 
  bind_rows(slutspelslag) %>% 
  bind_rows(skytteliga) %>% 
  bind_cols(namn) %>% 
  relocate(namn)

return(tips)

}

  
```

Test

```{r}
test <- em2021_clean(here("data/tips", "Leif Lindblad_EM-tipset2021.xlsx"))

```

Läs in alla excel-filer i en given mapp och lägg ut ett sammanhållet dataset

```{r}
em2021_tips_filer <- dir_ls(here("data/tips"), regexp = "\\.xlsx$")

em2021_tips <- em2021_tips_filer %>% 
  map_df(em2021_clean, .id = "fil") 

write_csv2(em2021_tips, here("data/tips", "em2021_tips.csv"))

```

